PinkCore/PinkCore/Areas/Admin/Controllers/ProductAdminController.cs
using AutoMapper;
using PinkCore.ActionFilters;
using PinkCore.Areas.Admin.ViewModels.Product;
using PinkCore.Models;
using PinkCore.Models.Cmind;
using PinkCore.Models.JoinModels;
using PinkCore.Repositories;
using PinkCore.Utility.Cmind;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PinkCore.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class ProductAdminController : BaseAdminController
    {
        private ProductRepository productRepository = new ProductRepository();
        private TopicRepository topicRepository = new TopicRepository();
        // GET: Admin/ProductAdmin
        public ActionResult Index(ProductIndexView model)
        {
            var query = productRepository.Query(model.Name, (int)model.Type, (int)Language.zh_TW, model.Status);
            var pageResult = query.ToPageResult<RelProductProductTranslations>(model);
            model.PageResult = Mapper.Map<PageResult<ProductIndexItemView>>(pageResult);
            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            var model = new ProductView();
            if (id != 0)
            {
                model = productRepository.FindBy(id);
            }
            else
            {
                DateTime dtCurrentTime;
                TimeZoneInfo tzi = TimeZoneInfo.FindSystemTimeZoneById("Taipei Standard Time");
                dtCurrentTime = TimeZoneInfo.ConvertTime(DateTime.Now, tzi);
                model.OnlineTime = dtCurrentTime.ToString("yyyy/MM/dd");
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ProductView model)
        {
            var imageHasFile = ImageHelper.CheckFileExists(model.ImageFile);
            var hoverImageHasFile = ImageHelper.CheckFileExists(model.HoverImageFile);

            model.SupportLan = model.supportLans != null ? string.Join(",", model.supportLans) : "";

            if (ModelState.IsValid)
            {
                Product data = Mapper.Map<Product>(model);

                var productTranslations = new List<ProductTranslations>();
                var productTranslationTw = Mapper.Map<ProductTranslations>(model.ProductTranslationViewTw);
                var productTranslationCn = Mapper.Map<ProductTranslations>(model.ProductTranslationViewCn);
                var productTranslationUs = Mapper.Map<ProductTranslations>(model.ProductTranslationViewUs);
                var productTranslationJp = Mapper.Map<ProductTranslations>(model.ProductTranslationViewJp);
                var productTranslationKr = Mapper.Map<ProductTranslations>(model.ProductTranslationViewKr);

                productTranslations.Add(productTranslationTw);
                productTranslations.Add(productTranslationCn);
                productTranslations.Add(productTranslationUs);
                productTranslations.Add(productTranslationJp);
                productTranslations.Add(productTranslationKr);

                var twImageHasFile = ImageHelper.CheckFileExists(model.ProductTranslationViewTw.ImageFile);
                var cnImageHasFile = ImageHelper.CheckFileExists(model.ProductTranslationViewCn.ImageFile);
                var usImageHasFile = ImageHelper.CheckFileExists(model.ProductTranslationViewUs.ImageFile);
                var jpImageHasFile = ImageHelper.CheckFileExists(model.ProductTranslationViewJp.ImageFile);
                var krImageHasFile = ImageHelper.CheckFileExists(model.ProductTranslationViewKr.ImageFile);


                if (twImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, productTranslationTw.Image);
                    productTranslationTw.Image = ImageHelper.SaveImage(PhotoFolder, model.ProductTranslationViewTw.ImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-Imagezh");
                }
                if (cnImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, productTranslationCn.Image);
                    productTranslationCn.Image = ImageHelper.SaveImage(PhotoFolder, model.ProductTranslationViewCn.ImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-Imagecn");
                }
                if (usImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, productTranslationUs.Image);
                    productTranslationUs.Image = ImageHelper.SaveImage(PhotoFolder, model.ProductTranslationViewUs.ImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-Imageus");
                }
                if (jpImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, productTranslationJp.Image);
                    productTranslationJp.Image = ImageHelper.SaveImage(PhotoFolder, model.ProductTranslationViewJp.ImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-Imagejp");
                }
                if (krImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, productTranslationKr.Image);
                    productTranslationKr.Image = ImageHelper.SaveImage(PhotoFolder, model.ProductTranslationViewKr.ImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-Imagekr");
                }

                var twHoverImageHasFile = ImageHelper.CheckFileExists(model.ProductTranslationViewTw.HoverImageFile);
                var cnHoverImageHasFile = ImageHelper.CheckFileExists(model.ProductTranslationViewCn.HoverImageFile);
                var usHoverImageHasFile = ImageHelper.CheckFileExists(model.ProductTranslationViewUs.HoverImageFile);
                var jpHoverImageHasFile = ImageHelper.CheckFileExists(model.ProductTranslationViewJp.HoverImageFile);
                var krHoverImageHasFile = ImageHelper.CheckFileExists(model.ProductTranslationViewKr.HoverImageFile);

                if (twHoverImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, productTranslationTw.HoverImage);
                    productTranslationTw.HoverImage = ImageHelper.SaveImage(PhotoFolder, model.ProductTranslationViewTw.HoverImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-HoverImagezh");
                }
                if (cnHoverImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, productTranslationCn.HoverImage);
                    productTranslationCn.HoverImage = ImageHelper.SaveImage(PhotoFolder, model.ProductTranslationViewCn.HoverImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-HoverImagecn");
                }
                if (usHoverImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, productTranslationUs.HoverImage);
                    productTranslationUs.HoverImage = ImageHelper.SaveImage(PhotoFolder, model.ProductTranslationViewUs.HoverImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-HoverImageus");
                }
                if (jpHoverImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, productTranslationJp.HoverImage);
                    productTranslationJp.HoverImage = ImageHelper.SaveImage(PhotoFolder, model.ProductTranslationViewJp.HoverImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-HoverImagejp");
                }
                if (krHoverImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, productTranslationKr.HoverImage);
                    productTranslationKr.HoverImage = ImageHelper.SaveImage(PhotoFolder, model.ProductTranslationViewKr.HoverImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-HoverImagekr");
                }

                if (imageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, data.Image);
                    data.Image = ImageHelper.SaveImage(PhotoFolder, model.ImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "Image");
                }
                if (hoverImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, data.HoverImage);
                    data.HoverImage = ImageHelper.SaveImage(PhotoFolder, model.HoverImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "HoverImage");
                }

                int adminId = AdminInfoHelper.GetAdminInfo().ID;
                data.Updater = adminId;
                DateTime onlineTime = DateTime.ParseExact(model.OnlineTime, "yyyy/MM/dd", null);
                data.OnlineTime = onlineTime;

                if (model.ID == 0)
                {
                    data.Creater = adminId;
                    model.ID = productRepository.Insert(data, productTranslations);
                }
                else
                {
                    productRepository.Update(data, productTranslations);
                }
                ShowMessage(true, "儲存成功");
                return RedirectToAction("Edit", new { id = model.ID });
            }

            return View(model);
        }

        public ActionResult Delete(int id)
        {
          
            var query = topicRepository.Query("",id,null,(int)Language.zh_TW);
            if (query.Any()) {
                ShowMessage(false, "請先刪除有包含此遊戲的話題，才能刪除此遊戲");

            }
            else {
                DeleteImage(id, (int)DeviceType.PC);
                DeleteImage(id, (int)DeviceType.PCHover);

                var images = productRepository.DeleteImages(id);

                foreach (var item in images)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, item);
                }
                var hoverImages = productRepository.DeleteHoverImages(id);
                foreach (var item in hoverImages)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, item);
                }
                productRepository.Delete(id);

PinkCore/PinkCore/Areas/Admin/Views/ProductAdmin/Index.cshtml
@using PinkCore.Models.Cmind;
@model PinkCore.Areas.Admin.ViewModels.Product.ProductIndexView
@{
    var title = "遊戲";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    @(title)管理
                </h1>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">搜尋</h3>
                </div>
                @using (Html.BeginForm("Index", "ProductAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    <div class="card-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @id = "inputTitle", @placeholder = "標題" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Type, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.DropDownListFor(model => model.Status, Model.TypeOptions, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Status, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.Status, "StatusDropDownList", new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">搜尋</button>
                                @Html.ActionLink("新增" + title, "Edit", "ProductAdmin", null, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">@(title)列表</h3>
                </div>
                <div class="card-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        @Html.Partial("_PageSizeAdmin", Model.PageResult)
                        <div class="row table-responsive no-padding">
                            <div class="col-sm-12">
                                <table class="table table-bordered table-hover table-striped dataTable dtr-inline">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Name)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Type)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.isHot)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Sort)
                                            </th>
                                            <th data-sorting="OnlineTime">
                                                @Html.DisplayNameFor(model => model.OnlineTime)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Status)
                                            </th>
                                            <th data-sorting="UpdateTime">
                                                @Html.DisplayNameFor(model => model.UpdateTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Name)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Type)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.isHot)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Sort)
                                            </th>
                                            <th data-sorting="OnlineTime">
                                                @Html.DisplayNameFor(model => model.OnlineTime)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Status)
                                            </th>
                                            <th data-sorting="UpdateTime">
                                                @Html.DisplayNameFor(model => model.UpdateTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach (var item in Model.PageResult.Data)
                                        {
                                            
                                        <tr>
                                            <td>@item.Name</td>
                                            <td>
                                                @PinkCore.Utility.Cmind.EnumHelper.GetDescription((ProductType)item.Type)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(model => item.isHot, "_Status")
                                            </td>

                                            <td>@item.Sort</td>
                                            <td>
                                                @Html.DisplayFor(model => item.OnlineTime, "_Date")
                                            </td>
                                            <td>
                                                @Html.DisplayFor(model => item.Status, "_Status")
                                            </td>
                                            <td>
                                                @Html.DisplayFor(model => item.UpdateTime, "DateTime")
                                            </td>
                                            <td>
                                                @Html.ActionLink("編輯", "Edit", "ProductAdmin", new { id = item.ID }, new { @class = "btn btn-primary" })
                                                @Html.ActionLink("刪除", "Delete", "ProductAdmin", new { id = item.ID }, new { @class = "btn btn-danger js-delete-confirm" })
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        @Html.Partial("_PageAdmin", Model.PageResult)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
}