PinkCore/PinkCore/Models/TopicImg.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinkCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicImg
    {
        public int ID { get; set; }
        public int TopicInformationId { get; set; }
        public int Language { get; set; }
        public string Image { get; set; }
        public int Sort { get; set; }
        public bool Status { get; set; }
    
        public virtual TopicInformation TopicInformation { get; set; }
    }
}

PinkCore/PinkCore/Models/TopicInformation.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinkCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopicInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TopicInformation()
        {
            this.TopicImgs = new HashSet<TopicImg>();
        }
    
        public int ID { get; set; }
        public int TopicTranslationsId { get; set; }
        public int Arrangement { get; set; }
        public string Title { get; set; }
        public string VideoUrl { get; set; }
        public bool Status { get; set; }
        public string Content { get; set; }
        public int Sort { get; set; }
        public int Language { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TopicImg> TopicImgs { get; set; }
        public virtual TopicTranslations TopicTranslations { get; set; }
    }
}

PinkCore/PinkCore/Areas/Admin/Controllers/TopicAdminController.cs
using AutoMapper;
using Newtonsoft.Json;
using PinkCore.ActionFilters;
using PinkCore.Areas.Admin.ViewModels.Topic;
using PinkCore.Models;
using PinkCore.Models.Cmind;
using PinkCore.Models.JoinModels;
using PinkCore.Repositories;
using PinkCore.Utility.Cmind;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace PinkCore.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class TopicAdminController : BaseAdminController
    {
        private TopicRepository topicRepository = new TopicRepository();

        // GET: Admin/TopicAdmin
        public ActionResult Index(TopicIndexView model)
        {
            var query = topicRepository.Query(model.Title, model.ProductId, model.Status, (int)Language.zh_TW);
            var pageResult = query.ToPageResult<RelTopicTopicTranslations>(model);
            model.PageResult = Mapper.Map<PageResult<TopicIndexItemView>>(pageResult);
            return View(model);
        }

        public ActionResult Edit(int id = 0)
        {
            var model = new TopicView();
            if (id != 0)
            {
                model = topicRepository.FindBy(id);
                DateTime dtCurrentTime = Convert.ToDateTime(model.OnlineTime);
                model.OnlineTime = dtCurrentTime.ToString("yyyy/MM/dd HH:mm");
            }
            else {
                DateTime dtCurrentTime;
                TimeZoneInfo tzi = TimeZoneInfo.FindSystemTimeZoneById("Taipei Standard Time");
                dtCurrentTime = TimeZoneInfo.ConvertTime(DateTime.Now, tzi);
                model.OnlineTime = dtCurrentTime.ToString("yyyy/MM/dd");
            }
            return View(model);
        }

        public ActionResult TopicInformation(int language)
        {
            return PartialView("_TopicInformation", new TopicInformationsView((Language)language));
        }

        public ActionResult TopicImgs(string collectionName)
        {
            ViewData["CollectionName"] = collectionName;
            return PartialView("_TopicImg", new TopicImgView());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Edit(TopicView model, FormCollection collection)
        {
            var tw_query = !string.IsNullOrEmpty(model.TopicTranslationViewTw.Title) ? topicRepository.FindIdByTitle(model.TopicTranslationViewTw.Title) : null;
            var jp_query = !string.IsNullOrEmpty(model.TopicTranslationViewJp.Title) ? topicRepository.FindIdByTitle(model.TopicTranslationViewJp.Title) : null;
            var kr_query = !string.IsNullOrEmpty(model.TopicTranslationViewKr.Title) ? topicRepository.FindIdByTitle(model.TopicTranslationViewKr.Title) : null;
            var cn_query = !string.IsNullOrEmpty(model.TopicTranslationViewCn.Title) ? topicRepository.FindIdByTitle(model.TopicTranslationViewCn.Title) : null;
            var us_query = !string.IsNullOrEmpty(model.TopicTranslationViewUs.Title) ? topicRepository.FindIdByTitle(model.TopicTranslationViewUs.Title) : null;

            bool isrepeat = false;
            if (tw_query != null || jp_query != null || kr_query != null || cn_query != null || us_query != null) 
            {
                var tw_title = model.TopicTranslationViewTw.Title;
                model.TopicTranslationViewTw.Title = model.TopicTranslationViewCn.Title == model.TopicTranslationViewTw.Title ? model.TopicTranslationViewTw.Title + " 繁" : model.TopicTranslationViewTw.Title;
                model.TopicTranslationViewCn.Title = model.TopicTranslationViewCn.Title == tw_title ? model.TopicTranslationViewCn.Title + " 簡" : model.TopicTranslationViewCn.Title;

                if (model.TopicTranslationViewTw.ID != 0)
                {
                    isrepeat = (tw_query != null && tw_query?.ID != model.TopicTranslationViewTw.ID)|| 
                            (jp_query != null && jp_query?.ID != model.TopicTranslationViewJp.ID) ||
                            (kr_query != null && kr_query?.ID != model.TopicTranslationViewKr.ID) ||
                            (cn_query != null && cn_query?.ID != model.TopicTranslationViewCn.ID) ||
                            (us_query!= null && us_query?.ID != model.TopicTranslationViewUs.ID);
                }
                else {
                    isrepeat = tw_query != null || jp_query != null || kr_query != null || cn_query != null || us_query != null;
                }

                if (isrepeat) {
                    ShowMessage(false, "標題不能跟其他話題重複");
                }
            }

            var imgHasFile = ImageHelper.CheckFileExists(model.ImageFile);
            var hoverimgHasFile = ImageHelper.CheckFileExists(model.HoverImageFile);
            var topicInformationszh_TWList = collection["TopicInformationszh_TW.Index"] != null ? collection["TopicInformationszh_TW.Index"].Split(',') : null;
            var topicInformationszh_CNList = collection["TopicInformationszh_CN.Index"] != null ? collection["TopicInformationszh_CN.Index"].Split(',') : null;
            var topicInformationsen_USList = collection["TopicInformationsen_US.Index"] != null ? collection["TopicInformationsen_US.Index"].Split(',') : null;
            var topicInformationsja_JPList = collection["TopicInformationsja_JP.Index"] != null ? collection["TopicInformationsja_JP.Index"].Split(',') : null;
            var topicInformationsko_KRList = collection["TopicInformationsko_KR.Index"] != null ? collection["TopicInformationsko_KR.Index"].Split(',') : null;

            if (topicInformationszh_TWList != null)
            {
                foreach (var item in topicInformationszh_TWList)
                {
                    if (collection["TopicInformationszh_TW[" + item + "].Status"] != null)
                    {
                        var status = collection["TopicInformationszh_TW[" + item + "].Status"].Split(',')[0];
                        var des = collection["TopicInformationszh_TW[" + item + "].Content"];
                        var topicimgs = collection["TopicInformationszh_TW[" + item + "].TopicImgs.Index"] != null ? collection["TopicInformationszh_TW[" + item + "].TopicImgs.Index"].Split(',') : null;
                        var imgsList = new List<TopicImgView>();
                        if (topicimgs != null)
                        {
                            foreach (var imgItem in topicimgs)
                            {
                                var statusimg = collection["TopicInformationszh_TW[" + item + "].TopicImgs[" + imgItem + "].Status"].Split(',')[0];
                                HttpPostedFileBase uploadFile = Request.Files["TopicInformationszh_TW[" + item + "].TopicImgs[" + imgItem + "].ImageFile"];
                                var ImgHasFile = ImageHelper.CheckFileExists(uploadFile);
                                var filename = "";
                                if (ImgHasFile)
                                {
                                    ImageHelper.DeletePhoto(PhotoFolder, collection["TopicInformationszh_TW[" + item + "].TopicImgs[" + imgItem + "].Image"]);
                                    filename = ImageHelper.SaveImage(PhotoFolder, uploadFile, Guid.NewGuid() + "-Imagezh");
                                }
                                imgsList.Add(new TopicImgView()
                                {
                                    Image = string.IsNullOrEmpty(filename) ? collection["TopicInformationszh_TW[" + item + "].TopicImgs[" + imgItem + "].Image"] : filename,
                                    Language = (int)Language.zh_TW,
                                    Sort = Convert.ToInt32(collection["TopicInformationszh_TW[" + item + "].TopicImgs[" + imgItem + "].Sort"]),
                                    Status = Convert.ToBoolean(statusimg),
                                });
                            }
                        }

                        model.TopicTranslationViewTw.TopicInformations.Add(new TopicInformationsView()
                        {
                            Title = collection["TopicInformationszh_TW[" + item + "].Title"],
                            Sort = Convert.ToInt32(collection["TopicInformationszh_TW[" + item + "].Sort"]),
                            Status = Convert.ToBoolean(status),
                            Arrangement = Convert.ToInt32(collection["TopicInformationszh_TW[" + item + "].Arrangement"]),
                            TopicTranslationsId = model.TopicTranslationViewTw.ID,
                            Content = des,
                            Language = Language.zh_TW,
                            VideoUrl = collection["TopicInformationszh_TW[" + item + "].VideoUrl"],
                            TopicImgs = imgsList
                        });
                    }
                }
            }

            if (topicInformationszh_CNList != null)
            {
                foreach (var item in topicInformationszh_CNList)
                {
                    if (collection["TopicInformationszh_CN[" + item + "].Status"] != null)
                    {
                        var status = collection["TopicInformationszh_CN[" + item + "].Status"].Split(',')[0];
                        var des = collection["TopicInformationszh_CN[" + item + "].Content"];
                        var topicimgs = collection["TopicInformationszh_CN[" + item + "].TopicImgs.Index"] != null ? collection["TopicInformationszh_CN[" + item + "].TopicImgs.Index"].Split(',') : null;
                        var imgsList = new List<TopicImgView>();
                        if (topicimgs != null)
                        {
                            foreach (var imgItem in topicimgs)
                            {

PinkCore/PinkCore/Areas/Admin/Views/TopicAdmin/Edit.cshtml
@using PinkCore.Models.Cmind;
@model PinkCore.Areas.Admin.ViewModels.Topic.TopicView
@{
    ViewBag.Title = "Edit";
    string title = Model.ID == 0 ? "新增話題" : "編輯話題";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        @title
    </h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card card-primary card-tabs">
                <div class="card-header p-0 pt-1">
                    <ul class="nav nav-tabs" id="custom-tabs-one-tab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="pill" href="#tab_1" role="tab" aria-controls="tab_1" aria-selected="true">共通</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="pill" href="#tab_2" role="tab" aria-controls="tab_2" aria-selected="false">繁體中文</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="pill" href="#tab_3" role="tab" aria-controls="tab_3" aria-selected="false">簡體中文</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="pill" href="#tab_4" role="tab" aria-controls="tab_4" aria-selected="false">英文</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="pill" href="#tab_5" role="tab" aria-controls="tab_5" aria-selected="false">日文</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="pill" href="#tab_6" role="tab" aria-controls="tab_6" aria-selected="false">韓文</a>
                        </li>
                    </ul>
                </div>
                @using (Html.BeginForm("Edit", "TopicAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)

                    <div class="card-body">
                        <div class="tab-content" id="custom-tabs-one-tabContent">
                            <div class="tab-pane fade show active" id="tab_1" role="tabpanel" aria-labelledby="custom-tabs-one-home-tab">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.Image)
                                            <span class="text-red">建議尺寸:寬1320px高700px，比例16:9</span>
                                            @Html.EditorFor(m => m.ImageFile, "_UploadImage")
                                            @if (!string.IsNullOrEmpty(Model.Image))
                                            {
                                                <img src="~/FileUploads/TopicPhoto/@Model.Image?v=@DateTime.Now.ToString("yyyyMMddHHmmss")" class="img-thumbnail" style="width:200px" />
                                                @Html.HiddenFor(model => model.Image)
                                                <br />
                                                @Html.ActionLink("刪除圖片", "DeleteImage", new { id = Model.ID, type = (int)DeviceType.PC }, new { @class = "btn btn-danger js-delete-confirm" })
                                            }
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.HoverImage)
                                            <span class="text-red">建議尺寸:寬1320px高700px，比例16:9</span>
                                            @Html.EditorFor(m => m.HoverImageFile, "_UploadImage")
                                            @if (!string.IsNullOrEmpty(Model.HoverImage))
                                            {
                                                <img src="~/FileUploads/TopicPhoto/@Model.HoverImage?v=@DateTime.Now.ToString("yyyyMMddHHmmss")" class="img-thumbnail" style="width:200px" />
                                                @Html.HiddenFor(model => model.HoverImage)
                                                <br />
                                                @Html.ActionLink("刪除圖片", "DeleteImage", new { id = Model.ID, type = (int)DeviceType.PCHover }, new { @class = "btn btn-danger js-delete-confirm" })
                                            }
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-4">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.ProductId)
                                            @Html.DropDownListFor(model => model.ProductId, Model.ProductOptions, new { @class = "form-control" })
                                        </div>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.OnlineTime)
                                            @Html.TextBoxFor(model => model.OnlineTime, new { @class = "form-control" })
                                            @Html.ValidationMessageFor(model => model.OnlineTime, "", new { @class = "text-danger" })
                                        </div>
                                    </div>
                                    <div class="col-md-2" style="margin-top:37px">
                                        <div class="form-check">
                                            @Html.CheckBoxFor(model => model.IsLimit, new { @class = "form-check-input" })
                                            <label class="form-check-label" for="check-box-status">
                                                @Html.DisplayNameFor(model => model.IsLimit)
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-md-2" style="margin-top:37px">
                                        <div class="form-check">
                                            @Html.CheckBoxFor(model => model.Status, new { @class = "form-check-input" })
                                            <label class="form-check-label" for="check-box-status">
                                                @Html.DisplayNameFor(model => model.Status)
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="tab_2" role="tabpanel" aria-labelledby="tab_2">
                                @Html.EditorFor(model => model.TopicTranslationViewTw, "TopicAdminEdit")
                            </div>
                            <div class="tab-pane fade" id="tab_3" role="tabpanel" aria-labelledby="tab_3">
                                @Html.EditorFor(model => model.TopicTranslationViewCn, "TopicAdminEdit")
                            </div>
                            <div class="tab-pane fade" id="tab_4" role="tabpanel" aria-labelledby="tab_4">
                                @Html.EditorFor(model => model.TopicTranslationViewUs, "TopicAdminEdit")
                            </div>
                            <div class="tab-pane fade" id="tab_5" role="tabpanel" aria-labelledby="tab_5">
                                @Html.EditorFor(model => model.TopicTranslationViewJp, "TopicAdminEdit")
                            </div>
                            <div class="tab-pane fade" id="tab_6" role="tabpanel" aria-labelledby="tab_6">
                                @Html.EditorFor(model => model.TopicTranslationViewKr, "TopicAdminEdit")
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">儲存</button>
                        @if (Model.ID != 0)
                        {
                            @Html.ActionLink("刪除本篇文章", "Delete", "TopicAdmin", new { id = Model.ID }, new { @class = "btn btn-danger js-delete-confirm" })
                        }
                        @Html.ActionLink("取消/回列表", "Index", "TopicAdmin", null, new { @class = "btn btn-default" })
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="~/Content/Admin/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/Admin/fileUpload.js"></script>
    <script src="~/Scripts/front/topic_edit.js"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <link href="~/Content/bootstrap-datetimepicker-master/css/bootstrap-datetimepicker.min.css" rel="stylesheet" />
    <script src="~/Content/bootstrap-datetimepicker-master/js/bootstrap-datetimepicker.js"></script>
    <!--taginput-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <script src="~/Content/bootstrap-tagsinput-latest/bootstrap-tagsinput.js"></script>
    <script type="text/javascript">
        $(function () {
            $('.js-arrangement').change();
            //Ckeditor init
            initCKeditor();
            var id = '@Model.ID'
            $(".topicDeleteLink").each(function () {
                var href = $(this).attr("href") + "&topicId=" + id;
                $(this).attr("href", href)
            });
            $.prototype.datetimepicker.DPGlobal.nonpunctuation = /[^ -\/:-@@\[-`{-~\t\n\rZ]+/g;
            var currentDate = new Date();
            if ($("#OnlineTime").val() === "0001/1/1 00:00") {
                $("#OnlineTime").val(currentDate.getFullYear() + '/' + (currentDate.getMonth() + 1) + '/' + currentDate.getDate() + ' ' + currentDate.getHours() + ":" + PrefixInteger(currentDate.getMinutes(), 2))
            } else {
                var strAry = $("#OnlineTime").val().split('/');
                var daytime = strAry[2].split(' ');
                var timestr = daytime ? daytime[1].split(':') : "00:00";
                var hourtime = parseInt(timestr[0]);
                $("#OnlineTime").val(strAry[0] + '/' + strAry[1] + '/' + daytime[0] + ' ' + hourtime + ":" + timestr[1])
            }
            currentDate.setFullYear(currentDate.getFullYear())
            currentDate.setMonth(0);
            currentDate.setDate(0);
            currentDate.setHours(0, 0, 0);
            $('#OnlineTime').datetimepicker({
                todayHighlight: true,
                weekStart: 1,
                minView: 0,
                autoclose: true,
                //pickerPosition: 'bottom-left',
                format: 'yyyy/mm/dd hh:ii ',
                //timezone: 'UTC',
                startDate: currentDate,
                disabledDate: false
            });
        });
        $('body').on('change', '.custom-file input[type="file"]', function () {
            const $this = $(this);
            var $customFile = $this.parent();
            var fileName = $this.val();
            var cleanFileName = fileName.replace('C:\\fakepath\\', " ");
            $customFile.find('.custom-file-label').html(cleanFileName);
        });
    </script>
}

PinkCore/PinkCore/Areas/Admin/Views/TopicAdmin/Index.cshtml
@using PinkCore.Models.Cmind;
@model PinkCore.Areas.Admin.ViewModels.Topic.TopicIndexView
@{
    var title = "話題";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>
                    @(title)管理
                </h1>
            </div>
        </div>
    </div>
</section>
<section class="content">
    <div class="row">
        <!--搜尋條件-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">搜尋</h3>
                </div>
                @using (Html.BeginForm("Index", "TopicAdmin", FormMethod.Get, new { @class = "form-horizontal" }))
                {
                    <div class="card-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Title, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @id = "inputTitle", @placeholder = "敘述" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.ProductId, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.DropDownListFor(model => model.ProductId, Model.ProductOptions, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Status, new { @class = "col-sm-2 control-label" })
                            <div class="col-sm-12">
                                @Html.EditorFor(model => model.Status, "StatusDropDownList", new { @class = "form-control" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-info">搜尋</button>
                                @Html.ActionLink("新增" + title, "Edit", "TopicAdmin", null, new { @class = "btn btn-primary" })
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <!--清單-->
        <div class="col-12">
            <div class="card">
                <div class="card-header with-border">
                    <h3 class="card-title">@(title)列表</h3>
                </div>
                <div class="card-body">
                    <div id="dataList_wrapper" class="dataTables_wrapper dt-bootstrap4">
                        @Html.Partial("_PageSizeAdmin", Model.PageResult)
                        <div class="row table-responsive no-padding">
                            <div class="col-sm-12">
                                <table class="table table-bordered table-hover table-striped dataTable dtr-inline">
                                    <thead>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Title)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.ProductId)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Status)
                                            </th>
                                            <th data-sorting="OnlineTime">
                                                @Html.DisplayNameFor(model => model.OnlineTime)
                                            </th>
                                            <th data-sorting="UpdateTime">
                                                @Html.DisplayNameFor(model => model.UpdateTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Title)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.Status)
                                            </th>
                                            <th>
                                                @Html.DisplayNameFor(model => model.ProductId)
                                            </th>
                                            <th data-sorting="OnlineTime">
                                                @Html.DisplayNameFor(model => model.OnlineTime)
                                            </th>
                                            <th data-sorting="UpdateTime">
                                                @Html.DisplayNameFor(model => model.UpdateTime)
                                            </th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                        @foreach (var item in Model.PageResult.Data)
                                        {
                                        <tr>
                                            <td>@item.Title</td>
                                            <td>@item.ProductName</td>
                                            <td>@Html.DisplayFor(model => item.Status, "_Status")</td>
                                            
                                            <td>@item.OnlineTime.ToString("yyyy/MM/dd HH:mm")</td>
                                            <td>
                                                @Html.DisplayFor(model => item.UpdateTime, "DateTime")
                                            </td>
                                            <td>
                                                @Html.ActionLink("編輯", "Edit", "TopicAdmin", new { id = item.ID }, new { @class = "btn btn-primary" })
                                                @Html.ActionLink("刪除", "Delete", "TopicAdmin", new { id = item.ID }, new { @class = "btn btn-danger js-delete-confirm" })
                                            </td>
                                        </tr>
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        @Html.Partial("_PageAdmin", Model.PageResult)
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/page.js"></script>
}