PinkCore/PinkCore/Areas/Admin/Controllers/AgeConfirmAdminController.cs
using AutoMapper;
using PinkCore.Areas.Admin.ViewModels.AgeConfirm;
using PinkCore.Models.Cmind;
using PinkCore.Models.JoinModels;
using PinkCore.Repositories;
using PinkCore.Models;
using PinkCore.Utility.Cmind;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PinkCore.ActionFilters;

namespace PinkCore.Areas.Admin.Controllers
{
    [Authorize]
    [ErrorHandleAdminActionFilter]
    public class AgeConfirmAdminController : BaseAdminController
    {
        private AgeConfirmRepository ageConfirmRepository = new AgeConfirmRepository();

        // GET: Admin/AgeConfirmAdmin
        public ActionResult Edit()
        {
            var model = new AgeConfirmView();
            var dataCount = ageConfirmRepository.GetAll().Count();

            if (dataCount == 0)
            {
                AgeConfirm data = Mapper.Map<AgeConfirm>(model);

                var ageConfirmTranslations = new List<AgeConfirmTranslations>();
                var ageConfirmTranslationTw = Mapper.Map<AgeConfirmTranslations>(model.AgeConfirmTranslationViewTw);
                var ageConfirmTranslationCn = Mapper.Map<AgeConfirmTranslations>(model.AgeConfirmTranslationViewCn);
                var ageConfirmTranslationUs = Mapper.Map<AgeConfirmTranslations>(model.AgeConfirmTranslationViewUs);
                var ageConfirmTranslationJp = Mapper.Map<AgeConfirmTranslations>(model.AgeConfirmTranslationViewJp);
                var ageConfirmTranslationKr = Mapper.Map<AgeConfirmTranslations>(model.AgeConfirmTranslationViewKr);

                ageConfirmTranslations.Add(ageConfirmTranslationTw);
                ageConfirmTranslations.Add(ageConfirmTranslationCn);
                ageConfirmTranslations.Add(ageConfirmTranslationUs);
                ageConfirmTranslations.Add(ageConfirmTranslationJp);
                ageConfirmTranslations.Add(ageConfirmTranslationKr);

                int adminId = AdminInfoHelper.GetAdminInfo().ID;
                data.Updater = adminId;
                data.Creater = adminId;
                ageConfirmRepository.Insert(data, ageConfirmTranslations);
            }
            else {
                model = ageConfirmRepository.FirstData();
                model.ID = ageConfirmRepository.FirstData().ID;
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AgeConfirmView model)
        {
            var pcImagehasFile = ImageHelper.CheckFileExists(model.PCImageFile);
            var moblieImagehasFile = ImageHelper.CheckFileExists(model.MoblieImageFile);

            if (ModelState.IsValid)
            {
                AgeConfirm data = Mapper.Map<AgeConfirm>(model);

                var ageConfirmTranslations = new List<AgeConfirmTranslations>();
                var ageConfirmTranslationTw = Mapper.Map<AgeConfirmTranslations>(model.AgeConfirmTranslationViewTw);
                var ageConfirmTranslationCn = Mapper.Map<AgeConfirmTranslations>(model.AgeConfirmTranslationViewCn);
                var ageConfirmTranslationUs = Mapper.Map<AgeConfirmTranslations>(model.AgeConfirmTranslationViewUs);
                var ageConfirmTranslationJp = Mapper.Map<AgeConfirmTranslations>(model.AgeConfirmTranslationViewJp);
                var ageConfirmTranslationKr = Mapper.Map<AgeConfirmTranslations>(model.AgeConfirmTranslationViewKr);

                ageConfirmTranslations.Add(ageConfirmTranslationTw);
                ageConfirmTranslations.Add(ageConfirmTranslationCn);
                ageConfirmTranslations.Add(ageConfirmTranslationUs);
                ageConfirmTranslations.Add(ageConfirmTranslationJp);
                ageConfirmTranslations.Add(ageConfirmTranslationKr);

                var twPCImageHasFile = ImageHelper.CheckFileExists(model.AgeConfirmTranslationViewTw.PCImageFile);
                var cnPCImageHasFile = ImageHelper.CheckFileExists(model.AgeConfirmTranslationViewCn.PCImageFile);
                var usPCImageHasFile = ImageHelper.CheckFileExists(model.AgeConfirmTranslationViewUs.PCImageFile);
                var jpPCImageHasFile = ImageHelper.CheckFileExists(model.AgeConfirmTranslationViewJp.PCImageFile);
                var krPCImageHasFile = ImageHelper.CheckFileExists(model.AgeConfirmTranslationViewKr.PCImageFile);

                var twMoblieImageHasFile = ImageHelper.CheckFileExists(model.AgeConfirmTranslationViewTw.MoblieImageFile);
                var cnMoblieImageHasFile = ImageHelper.CheckFileExists(model.AgeConfirmTranslationViewCn.MoblieImageFile);
                var usMoblieImageHasFile = ImageHelper.CheckFileExists(model.AgeConfirmTranslationViewUs.MoblieImageFile);
                var jpMoblieImageHasFile = ImageHelper.CheckFileExists(model.AgeConfirmTranslationViewJp.MoblieImageFile);
                var krMoblieImageHasFile = ImageHelper.CheckFileExists(model.AgeConfirmTranslationViewKr.MoblieImageFile);

                if (twPCImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, ageConfirmTranslationTw.PCImage);
                    ageConfirmTranslationTw.PCImage = ImageHelper.SaveImage(PhotoFolder, model.AgeConfirmTranslationViewTw.PCImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff")+ "-PCImagezh");
                }
                if (cnPCImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, ageConfirmTranslationCn.PCImage);
                    ageConfirmTranslationCn.PCImage = ImageHelper.SaveImage(PhotoFolder, model.AgeConfirmTranslationViewCn.PCImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-PCImagecn");
                }
                if (usPCImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, ageConfirmTranslationUs.PCImage);
                    ageConfirmTranslationUs.PCImage = ImageHelper.SaveImage(PhotoFolder, model.AgeConfirmTranslationViewUs.PCImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-PCImageus");
                }
                if (jpPCImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, ageConfirmTranslationJp.PCImage);
                    ageConfirmTranslationJp.PCImage = ImageHelper.SaveImage(PhotoFolder, model.AgeConfirmTranslationViewJp.PCImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-PCImagejp");
                }
                if (krPCImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, ageConfirmTranslationKr.PCImage);
                    ageConfirmTranslationKr.PCImage = ImageHelper.SaveImage(PhotoFolder, model.AgeConfirmTranslationViewKr.PCImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-PCImagekr");
                }

                if (twMoblieImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, ageConfirmTranslationTw.MoblieImage);
                    ageConfirmTranslationTw.MoblieImage = ImageHelper.SaveImage(PhotoFolder, model.AgeConfirmTranslationViewTw.MoblieImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-MoblieImagezh");
                }
                if (cnMoblieImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, ageConfirmTranslationCn.MoblieImage);
                    ageConfirmTranslationCn.MoblieImage = ImageHelper.SaveImage(PhotoFolder, model.AgeConfirmTranslationViewCn.MoblieImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-MoblieImagecn");
                }
                if (usMoblieImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, ageConfirmTranslationUs.MoblieImage);
                    ageConfirmTranslationUs.MoblieImage = ImageHelper.SaveImage(PhotoFolder, model.AgeConfirmTranslationViewUs.MoblieImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-MoblieImageus");
                }
                if (jpMoblieImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, ageConfirmTranslationJp.MoblieImage);
                    ageConfirmTranslationJp.MoblieImage = ImageHelper.SaveImage(PhotoFolder, model.AgeConfirmTranslationViewJp.MoblieImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-MoblieImagejp");
                }
                if (krMoblieImageHasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, ageConfirmTranslationKr.MoblieImage);
                    ageConfirmTranslationKr.MoblieImage = ImageHelper.SaveImage(PhotoFolder, model.AgeConfirmTranslationViewKr.MoblieImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-MoblieImagekr");
                }

                if (pcImagehasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, data.PCImage);
                    data.PCImage = ImageHelper.SaveImage(PhotoFolder, model.PCImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-PCImage");
                }
                if (moblieImagehasFile)
                {
                    ImageHelper.DeletePhoto(PhotoFolder, data.MoblieImage);
                    data.MoblieImage = ImageHelper.SaveImage(PhotoFolder, model.MoblieImageFile, DateTime.Now.ToString("yyyyMMddhhmmssfff") + "-MoblieImage");
                }

                int adminId = AdminInfoHelper.GetAdminInfo().ID;
                data.Updater = adminId;

                //if (model.ID == 0)
                //{
                //    data.Creater = adminId;
                //    model.ID = ageConfirmRepository.Insert(data, ageConfirmTranslations);
                //}
                //else
                //{
                    ageConfirmRepository.Update(data, ageConfirmTranslations);
                //}
                ShowMessage(true, "儲存成功");
                return RedirectToAction("Edit", new { id = model.ID });
            }

            return View(model);
        }

        public ActionResult DeleteImage(int id, int type, int language = 0)

PinkCore/PinkCore/Areas/Admin/Views/AgeConfirmAdmin/Edit.cshtml
@using PinkCore.Models.Cmind;
@model PinkCore.Areas.Admin.ViewModels.AgeConfirm.AgeConfirmView
@{
    ViewBag.Title = "Edit";
    string title = Model.ID == 0 ? "新增年齡確認" : "編輯年齡確認";
}

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        @title
    </h1>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card card-primary card-tabs">
                <div class="card-header p-0 pt-1">
                    <ul class="nav nav-tabs" id="custom-tabs-one-tab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" data-toggle="pill" href="#tab_1" role="tab" aria-controls="tab_1" aria-selected="true">共通</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="pill" href="#tab_2" role="tab" aria-controls="tab_2" aria-selected="false">繁體中文</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="pill" href="#tab_3" role="tab" aria-controls="tab_3" aria-selected="false">簡體中文</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="pill" href="#tab_4" role="tab" aria-controls="tab_4" aria-selected="false">英文</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="pill" href="#tab_5" role="tab" aria-controls="tab_5" aria-selected="false">日文</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="pill" href="#tab_6" role="tab" aria-controls="tab_6" aria-selected="false">韓文</a>
                        </li>
                    </ul>
                </div>
                @using (Html.BeginForm("Edit", "AgeConfirmAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)

                    <div class="card-body">
                        <div class="tab-content" id="custom-tabs-one-tabContent">
                            <div class="tab-pane fade show active" id="tab_1" role="tabpanel" aria-labelledby="custom-tabs-one-home-tab">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.PCImage)
                                            @*<span class="text-red">建議尺寸</span>*@
                                            <div class="input-group">
                                                @Html.EditorFor(m => m.PCImageFile, "_UploadImage")
                                            </div>
                                            @if (!string.IsNullOrEmpty(Model.PCImage))
                                            {
                                                <img src="~/FileUploads/AgeConfirmPhoto/@Model.PCImage?v=@DateTime.Now.ToString("yyyyMMddHHmmss")" class="img-thumbnail" style="height:150px" />
                                                @Html.HiddenFor(model => model.PCImage)
                                                <br />
                                                @Html.ActionLink("刪除圖片", "DeleteImage", new { id = Model.ID, type = (int)DeviceType.PC }, new { @class = "btn btn-danger js-delete-confirm" })
                                            }

                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            @Html.LabelFor(m => m.MoblieImage)
                                            @*<span class="text-red">(高100寬100px*高度自訂)</span>*@
                                            <div class="input-group">
                                                @Html.EditorFor(m => m.MoblieImageFile, "_UploadImage")
                                            </div>
                                            @if (!string.IsNullOrEmpty(Model.MoblieImage))
                                            {
                                                <img src="~/FileUploads/AgeConfirmPhoto/@Model.MoblieImage?v=@DateTime.Now.ToString("yyyyMMddHHmmss")" class="img-thumbnail" style="height:150px" />
                                                @Html.HiddenFor(model => model.MoblieImage)
                                                <br />
                                                @Html.ActionLink("刪除圖片", "DeleteImage", new { id = Model.ID, type = (int)DeviceType.Moblie }, new { @class = "btn btn-danger js-delete-confirm" })
                                            }

                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="tab_2" role="tabpanel" aria-labelledby="tab_2">
                                @Html.EditorFor(model => model.AgeConfirmTranslationViewTw, "AgeConfirmAdminEdit")
                            </div>
                            <div class="tab-pane fade" id="tab_3" role="tabpanel" aria-labelledby="tab_3">
                                @Html.EditorFor(model => model.AgeConfirmTranslationViewCn, "AgeConfirmAdminEdit")
                            </div>
                            <div class="tab-pane fade" id="tab_4" role="tabpanel" aria-labelledby="tab_4">
                                @Html.EditorFor(model => model.AgeConfirmTranslationViewUs, "AgeConfirmAdminEdit")
                            </div>
                            <div class="tab-pane fade" id="tab_5" role="tabpanel" aria-labelledby="tab_5">
                                @Html.EditorFor(model => model.AgeConfirmTranslationViewJp, "AgeConfirmAdminEdit")
                            </div>
                            <div class="tab-pane fade" id="tab_6" role="tabpanel" aria-labelledby="tab_6">
                                @Html.EditorFor(model => model.AgeConfirmTranslationViewKr, "AgeConfirmAdminEdit")
                            </div>
                        </div>
                    </div>

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary">儲存</button>
                        @Html.ActionLink("取消/回列表", "Index", "AgeConfirmAdmin", null, new { @class = "btn btn-default" })
                    </div>
                }
            </div>
        </div>
    </div>
</section>

@section scripts{
    <script src="~/Scripts/Admin/fileUpload.js"></script>
    <script src="~/Content/Admin/ckeditor/ckeditor.js"></script>
    <script src="~/Scripts/jquery.validate.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function () {
            //Ckeditor init
            $(window).on('load', function () {
                $("form").each(function () { $.data($(this)[0], 'validator', false); });
                $.validator.unobtrusive.parse("form");
            });
            $('.js-ckeditor').each(function (i, e) {
                var id = $(e).attr('id');
                CKEDITOR.replace(id, {
                    customConfig: '/Content/Admin/ckeditor/ckeditor_custom_config.js',
                    filebrowserImageUploadUrl: "/Admin/AgeConfirmAdmin/Upload",

                });
            });
        });
        $('body').on('change', '.custom-file input[type="file"]', function () {
            const $this = $(this);
            var $customFile = $this.parent();

            var fileName = $this.val();
            var cleanFileName = fileName.replace('C:\\fakepath\\', " ");
            $customFile.find('.custom-file-label').html(cleanFileName);
        });
    </script>
}