PinkCore/PinkCore/Areas/Admin/ViewModels/Topic/TopicIndexView.cs
using PinkCore.Models.Cmind;
using PinkCore.Repositories;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PinkCore.Areas.Admin.ViewModels.Topic
{
    public class TopicIndexView : TopicQuery
    {
        public PageResult<TopicIndexItemView> PageResult { get; set; }
    }

    public class TopicIndexItemView
    {
        ProductRepository productRepository = new ProductRepository();

        public int ID { get; set; }

        [Display(Name = "標題")]
        public string Title { get; set; }

        [Display(Name = "遊戲")]
        public int ProductId { get; set; }

        [Display(Name = "啟用狀態")]
        public bool Status { get; set; }


        public string ProductName
        {
            get
            {
                var result = productRepository.FindBy(ProductId).ProductTranslationViewTw.Name;
                return result;
            }
        }

        [Display(Name = "上線日期")]
        public DateTime OnlineTime { get; set; }

        [Display(Name = "更新日期")]
        public DateTime UpdateTime { get; set; }
    }
}

PinkCore/PinkCore/Areas/Admin/ViewModels/Topic/TopicQuery.cs
using PinkCore.Models.Cmind;
using PinkCore.Repositories;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PinkCore.Areas.Admin.ViewModels.Topic
{
    public class TopicQuery : PageQuery
    {
        public TopicQuery()
        {
            this.Sorting = "OnlineTime";
            this.isDescending = true;
        }

        public int ID { get; set; }

        [Display(Name = "標題")]
        public string Title { get; set; }

        [Display(Name = "上線日期")]
        public DateTime OnlineTime { get; set; }

        [Display(Name = "遊戲")]
        public int ProductId { get; set; }

        [Display(Name = "啟用狀態")]
        public bool ? Status { get; set; }

        ProductRepository productRepository = new ProductRepository();

        public List<SelectListItem> ProductOptions
        {
            get
            {
                var result = new List<SelectListItem>();
                var values = productRepository.GetAll().Where(p => p.Language == (int)Language.zh_TW);
                result.Insert(0, new SelectListItem { Text = "全部", Value = "0" });
                foreach (var v in values)
                {
                    result.Add(new SelectListItem()
                    {
                        Value = v.ID.ToString(),
                        Text = v.Name
                    });
                }
                return result;
            }
        }


        [Display(Name = "更新日期")]
        public DateTime UpdateTime { get; set; }
    }
}

PinkCore/PinkCore/Areas/Admin/ViewModels/Topic/TopicView.cs
using PinkCore.Models.Cmind;
using PinkCore.Repositories;
using PinkCore.Utility.Cmind;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PinkCore.Areas.Admin.ViewModels.Topic
{
    public class TopicView
    {
        public TopicView()
        {
            TopicTranslationViewTw = new TopicTranslationView(Language.zh_TW);
            TopicTranslationViewCn = new TopicTranslationView(Language.zh_CN);
            TopicTranslationViewUs = new TopicTranslationView(Language.en_US);
            TopicTranslationViewKr = new TopicTranslationView(Language.ko_KR);
            TopicTranslationViewJp = new TopicTranslationView(Language.ja_JP);
            ProductRepository productRepository = new ProductRepository();

            var values = productRepository.Query(null, 0,(int)Language.zh_TW, null);
            List<SelectListItem> options = values.Select(p => new SelectListItem()
            {
                Text = p.Name,
                Value = p.ID.ToString()
            }).ToList();
            this.ProductOptions = options;
        }

        public int ID { get; set; }

        [Display(Name = "圖片")]
        public string Image { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [Display(Name = "我只想看帥哥分類")]
        public bool IsLimit { get; set; }

        [Display(Name = "啟用狀態")]
        public bool Status { get; set; }

        [Display(Name = "電腦版替換圖")]
        public string HoverImage { get; set; }
        public HttpPostedFileBase HoverImageFile { get; set; }

        [Display(Name = "相關遊戲")]
        public int ProductId { get; set; }

        public List<SelectListItem> ProductOptions { get; set; }


        [Display(Name = "上線日期")]
        public string OnlineTime { get; set; }

        public System.DateTime CreateTime { get; set; }

        public int Creater { get; set; }

        [Display(Name = "更新日期")]
        public System.DateTime UpdateTime { get; set; }

        public int Updater { get; set; }

        public TopicTranslationView TopicTranslationViewTw { get; set; }

        public TopicTranslationView TopicTranslationViewCn { get; set; }

        public TopicTranslationView TopicTranslationViewUs { get; set; }

        public TopicTranslationView TopicTranslationViewJp { get; set; }

        public TopicTranslationView TopicTranslationViewKr { get; set; }
    }

    public class TopicTranslationView
    {
        public TopicTranslationView() { }
        public TopicTranslationView(Language language)
        {
            this.TopicInformations = new List<TopicInformationsView>();
            this.Language = language;
        }
        public int ID { get; set; }
        public int TopicId { get; set; }
        public Language Language { get; set; }

        [Display(Name = "圖片")]
        public string Image { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [Display(Name = "電腦版替換圖")]
        public string HoverImage { get; set; }
        public HttpPostedFileBase HoverImageFile { get; set; }

        [Display(Name = "標題")]
        [StringLength(60, ErrorMessage = "{0} 不能超過{1}字. ")]
        public string Title { get; set; }

        [Display(Name = "前台連結")]
        public string LinkUrl { get; set; }

        [Display(Name = "標籤")]
        [StringLength(52, ErrorMessage = "{0} 不能超過{1}字. ")]
        public string Tags { get; set; }

        public List<TopicInformationsView> TopicInformations { get; set; }
    }
    public class TopicInformationsView {

        public TopicInformationsView(Language language = 0)
        {
            this.ItemIndex = Guid.NewGuid();
            this.TopicImgs = new List<TopicImgView>();
            this.Language = language;
            var values = EnumHelper.GetValues<ArrangementType>();
            List<SelectListItem> options = values.Select(p => new SelectListItem()
            {
                Text = string.Format("{0} ({1})", p, EnumHelper.GetDescription(p)),
                Value = ((int)p).ToString()
            }).ToList();
            this.ArrangementOptions = options;
        }
        public int ID { get; set; }

        public Language Language { get; set; }

        public Guid ItemIndex { get; set; }

        public int TopicTranslationsId { get; set; }

        [Display(Name = "排版類型")]
        public int Arrangement { get; set; }

        [Display(Name = "前台連結")]
        public string LinkUrl { get; set; }

        [Display(Name = "影片連結")]
        public string VideoUrl { get; set; }

        [Display(Name = "標題")]
        [StringLength(60, ErrorMessage = "{0} 不能超過{1}字. ")]
        public string Title { get; set; }

        [AllowHtml]
        [Display(Name = "內容")]
        public string Content { get; set; }

        [Display(Name = "啟用狀態")]
        public bool Status { get; set; }

        [Display(Name = "排序")]
        public int Sort { get; set; }

        public List<SelectListItem> ArrangementOptions { get; set; }

        public List<TopicImgView> TopicImgs { get; set; }
    }

    public class TopicImgView
    {
        public int ID { get; set; }

        public int TopicInformationId { get; set; }

        [Display(Name = "語言")]
        public int Language { get; set; }

        [Display(Name = "圖片")]
        public string Image { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        [Display(Name = "排序")]
        public int Sort { get; set; }

        [Display(Name = "啟用狀態")]
        public bool Status { get; set; }
    }
}

PinkCore/PinkCore/Models/Topic.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PinkCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int ID { get; set; }
        public int ProductId { get; set; }
        public string HoverImage { get; set; }
        public string Image { get; set; }
        public bool IsLimit { get; set; }
        public bool Status { get; set; }
        public System.DateTime OnlineTime { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Creater { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public int Updater { get; set; }
    }
}

PinkCore/PinkCore/Controllers/TopicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using PinkCore.ActionFilters;
using PinkCore.Models.Cmind;
using PinkCore.Repositories;
using PinkCore.ViewModels.Game;
using PinkCore.ViewModels.Topic;

namespace PinkCore.Controllers
{
    [LayoutActionFilter]
    [ErrorHandleActionFilter]
    public class TopicController : BaseController
    {
        private TopicRepository topicRepository = new TopicRepository();
        private ProductRepository productRepository = new ProductRepository();

        // GET: Topic
        public ActionResult Index(int game = 0)
        {
            var language = GetLanguage();
            var category = GetCategory();
          
            TopicView model = new TopicView();
            var topicQuery = topicRepository.List(game,language, category);
            var allTopicQuery = topicRepository.List(0, language, category);
            model.DataList = Mapper.Map<IEnumerable<TopicItem>>(topicQuery);
            model.AllDataList = Mapper.Map<IEnumerable<TopicItem>>(allTopicQuery);
            model.IsCookie = GetCategory() != null ? true: false ;
            return View(model);
        }
        public ActionResult Detail(string id)
        {
            var language = GetLanguage();
            var category = GetCategory();
            var model = new TopicItem();

            if (string.IsNullOrEmpty(id) || id == "Index")
            {
                return RedirectToAction("Detail", new { lang = HttpContext.Request.RequestContext.RouteData.Values["lang"].ToString() });
            }

            //string name = redirectToFriendUrl(id);
            //if (!string.IsNullOrEmpty(name))
            //{
            //    return RedirectToAction("Detail", new { id = name });
            //}
            int numId = 0;
            if (!string.IsNullOrEmpty(id) && !int.TryParse(id, out numId))
            {
                var topicdata = topicRepository.FindIdByLinkTitle(id, (int)language);
                if (topicdata == null)
                {
                    topicdata = topicRepository.FindTopicIdByLinkTitle(id);
                    var topicId = topicdata.TopicId;
                    var query = topicRepository.Detail(topicId, language, category);

                    var name =  !string.IsNullOrEmpty(query.LinkUrl) ? query.LinkUrl : topicId.ToString();

                    return RedirectToAction("Detail", new { id = name });
                }
                else {
                    var topicId = topicdata.TopicId;
                    var query = topicRepository.Detail(topicId, language, category);
                    query.TopicInformations = topicdata.TopicInformations.ToList();
                    if (query != null)
                    {
                        model = Mapper.Map<TopicItem>(query);
                        model.IsMoblie = IsFromMobile();
                        var gameQuery = productRepository.Detail(model.ProductId, language, category);
                        model.GameData = Mapper.Map<GameItem>(gameQuery);
                        var topicQuery = topicRepository.List(0, language, category);
                        model.DataList = Mapper.Map<IEnumerable<TopicItem>>(topicQuery);
                    }
                    else
                    {
                        return RedirectToAction("Error", new { lang = HttpContext.Request.RequestContext.RouteData.Values["lang"].ToString() });
                    }
                }
               
            }
            if(int.TryParse(id, out numId)){
                var query = topicRepository.Detail(numId, language, category);
                if (query != null)
                {
                    if (!string.IsNullOrEmpty(query.LinkUrl))
                    {
                        return RedirectToAction("Detail", new { id = query.LinkUrl });
                    }
                    model = Mapper.Map<TopicItem>(query);
                    model.IsMoblie = IsFromMobile();
                    var gameQuery = productRepository.Detail(model.ProductId, language, category);
                    model.GameData = Mapper.Map<GameItem>(gameQuery);
                    var topicQuery = topicRepository.List(0, language, category);
                    model.DataList = Mapper.Map<IEnumerable<TopicItem>>(topicQuery);
                }
                else
                {
                    return RedirectToAction("Error", new { lang = HttpContext.Request.RequestContext.RouteData.Values["lang"].ToString() });
                }
            }
            return View(model);
        }

        private string redirectToFriendUrl(string id)
        {
            var language = GetLanguage();
            var category = GetCategory();
            string name = string.Empty;
            int numId = 0;
            if (int.TryParse(id, out numId))
            {
                var data = topicRepository.Detail(numId, language,category);
                if (data != null)
                {
                    if (!string.IsNullOrEmpty(data.LinkUrl))
                    {
                        name = data.LinkUrl;
                    }
                    else
                    {
                        var twdata = topicRepository.Detail(numId, language, category);
                        name = Regex.Replace(twdata.LinkUrl, @"\s", "-");
                    }
                }

            }
          
            return name;
        }

        [PreviewAuthorizeActionFilters]
        public ActionResult Preview(int id)
        {
            var language = GetLanguage();
            var query = topicRepository.Preview(id, language);

            if (query == null)
            {
                return RedirectToAction("NotFound");
            }
            var model = new TopicItem();
            model = Mapper.Map<TopicItem>(query);
            model.IsMoblie = IsFromMobile();
            var gameQuery = productRepository.Preview(model.ProductId, language);
            model.GameData = Mapper.Map<GameItem>(gameQuery);
            var gameId = model.GameData != null ? model.GameData.ID : 0;
            var topicQuery = topicRepository.Query(null ,gameId, true, (int)language);
            model.DataList = Mapper.Map<IEnumerable<TopicItem>>(topicQuery);
            return View("Detail", model);
        }
    }
}

PinkCore/PinkCore/Views/Topic/Index.cshtml
@model PinkCore.ViewModels.Topic.TopicView
@{
    var scriptfile = "";
    string url = Request.Url.Scheme + "://" + Request.Url.Authority;
    string absolutePath = Request.Url.AbsolutePath;
    var lang = absolutePath.IndexOf("-") != -1 ? absolutePath.Substring(0, 6) : "/";
    switch (lang)
    {
        case "/zh-TW":
            scriptfile = "seo_home_tw.json";
            break;
        case "/zh-CN":
            scriptfile = "seo_home_cn.json";
            break;
        case "/en-US":
            scriptfile = "seo_home_en.json";
            break;
        case "/ja-JP":
            scriptfile = "seo_home_jp.json";
            break;
        case "/ko-KR":
            scriptfile = "seo_home_kr.json";
            break;
        case "/":
            scriptfile = "seo_home_tw.json";
            break;
    }
}
@section head{

    <meta property="og:image" content="@url/Content/pinkcore/img/og.jpg">
    <meta property="og:image:type" content="image/jpeg">
    <meta name="twitter:image" content="@url/Content/pinkcore/img/og.jpg">
    @if (Model.DataList.Any())
    {
        <title>Pinkcore | @PinkCore.Resources._Layout.Index.Topics</title>
        <meta name="twitter:title" content="Pinkcore | @PinkCore.Resources._Layout.Index.Topics" />
        <meta property="og:title" content="Pinkcore | @PinkCore.Resources._Layout.Index.Topics" />
        if (Model.AllDataList.First().TopicInformations.Any())
        {
            string content = System.Text.RegularExpressions.Regex.Replace(Model.AllDataList.First().TopicInformations[0]?.Content, @"\<.*?\>", String.Empty).Replace("&nbsp;", String.Empty).Trim();
            if (content.Count() > 60)
            {
                content = content.Substring(0, 60);
            }
            <meta property="og:description" content="@content" />
            <meta name="description" content="@content" />
            <meta name="twitter:description" content="@content" />
        }
    }

}
<section class="py-5">
    <div class="container">
        <div class="row gx-0 gy-5 justify-center">
            <div class="col-12 col-l-6 col-xl-12 txt-sand txt-center tracking-xl-widest">
                <h1 class="feature-3">
                    @PinkCore.Resources.Topic.Index.LatestNews
                    <span class="pseudo-dsshed txt-md block">TOPICS</span>
                </h1>
                <div class="hr"></div>
            </div>
            <div class="col-8 col-m-5 col-l-10">
                <!--==========下拉選單(可做共用)==========-->
                <div class="btn-group btn-group-sand flex">
                    <button class="btn btn-selected txt-left hidden-l" id="dropdownText" type="button">All</button>
                    <button class="btn dropdown-toggle dropdown-toggle-split grow-0 hidden-l" id="dropdownMenuReference" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-reference="parent"><span class="sr-only">Toggle Dropdown</span></button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuReference">
                        <a class="dropdown-item" href="@Url.Action("Index","Topic")" title="All">All</a>
                        @foreach (var item in Model.AllDataList.GroupBy(d => new { d.ProductId }).Select(m => new { m.Key.ProductId, m.ToList().First().ProductName }))
                        {
                            <a class="dropdown-item" data-game="@item.ProductId" data-gamename="@item.ProductName" href="@Url.Action("Index","Topic", new { game = item.ProductId })" title="@item.ProductName">@item.ProductName</a>
                        }
                    </div>
                </div>
            </div>
            <div class="topic grid col-12 col-m-9 col-l-10 col-mx-l-1">
                @foreach (var item in Model.DataList.Select((value, index) => new { value, index }))
                {
                    var css = item.index == 0 || item.index > 4 ? "col-l-12" : "col-l-8 col-xl-7";
                    var css2 = item.index == 0 || item.index > 4 ? "col-l-12 grow-1-l" : "col-l-4 col-xl-5";
                    <div class="cell py-3 px-m-2 px-1 p-l-0 hover-area @(item.index > 10 ? "init hidden" : "" )">
                        <div class="row gx-m-2 gx-1 gx-l-0">
                            <div class="col-5 col-m-7 @css">
                                <img class="img-fluid" src="~/FileUploads/TopicPhoto/@(!string.IsNullOrEmpty(item.value.TranslationsImage) ? item.value.TranslationsImage : item.value.Image)" alt="@item.value.Title" title="@item.value.Title" loading="eager">
                                <div class="bg-cover hover-fadein-img" style="background-image:url('/FileUploads/TopicPhoto/@(!string.IsNullOrEmpty(item.value.TranslationsHoverImage) ? item.value.TranslationsHoverImage : item.value.HoverImage)');"></div>
                            </div>
                            <div class="col-7 col-m-5 @css2 static">
                                <div class="topic-content">
                                    <h2 class="topic-title">
                                        @if (!string.IsNullOrEmpty(item.value.Title))
                                        {
                                            var title = item.value.Title.Length > 22 ? item.value.Title.Substring(0, 22) + "..." : item.value.Title;
                                            <a class="stretched-link" href="@Url.Action("Detail", "Topic", new { id = item.value.LinkUrl })" title="@title">@title</a>
                                        }
                                        else
                                        {
                                            <a class="stretched-link" href="@Url.Action("Detail", "Topic", new { id = item.value.ID })"></a>
                                        }
                                    </h2>
                                    <p>
                                        @if (!string.IsNullOrEmpty(item.value.Tags))
                                        {
                                            var taglist = item.value.Tags.Split(',');
                                            foreach (var tag in taglist)
                                            {
                                                <span class="badge">@tag</span>}
                                        }
                                        <br>
                                        @{ DateTime DateObject = Convert.ToDateTime(Html.DisplayFor(m => item.value.OnlineTime, "DateTime").ToString());}
                                        <time class="hidden block-l">@DateObject.ToString("yyyy.MM.dd")</time>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>
            @if (Model.DataList.Count() > 11)
            {
                <div class="col-8 col-m-5 col-l-3 col-xl-2">
                    <button class="btn btn-sand-grad show-all" type="button">@PinkCore.Resources.Topic.Index.AllNews</button>
                </div>
            }
        </div>
    </div>
</section>
@section scripts{
    <script>
       // Add a schema tag to your
       $.getJSON( "/Content/pinkcore/js/@scriptfile", function( data ) {
         $( "<script/>", {
           "type": "application/ld+json",
           "html": JSON.stringify(data)
         }).appendTo( "head" );
       });
        $(function () {
            var queryString = location.search;
            let params = new URLSearchParams(queryString);
            let gameparams = params.get("game");
            if (gameparams) {
                $(".dropdown-item").each(function () {
                    var $this = $(this).data("game");
                    var gamename = $(this).data("gamename");
                    if ($this == gameparams) {
                        console.log(gamename)
                        $("#dropdownText").text(gamename);
                    }
                });
            }
        });
    </script>
}